# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage: build
FROM node:lts-alpine AS builder
WORKDIR /app
# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts
# Copy source and build
COPY . .
RUN npm run build

# Stage: production
FROM node:lts-alpine AS runtime
WORKDIR /app
# Copy built artifacts and deps
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
# Expose stdio usage (no port)
# Default command
CMD ["node", "build/index.js"]
